databases:
  - name: avm
    databaseName: avmjalore
    user: avmjalore_user

services:
  - type: web
    name: avm
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn avm.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: avmjalore
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4