# Generated by Django 4.2.5 on 2023-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avmjalore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avmform',
            name='image',
        ),
        migrations.AddField(
            model_name='avmform',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
