# Generated by Django 4.2.6 on 2023-10-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avmjalore', '0002_remove_avmform_image_avmform_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='avmform',
            name='DOW',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avmform',
            name='image_url',
            field=models.TextField(),
        ),
    ]
